### ISSUE TITLE
Can't export to tflite...

### ISSUE THREAD

**Issue by yanfeiwong** [GreenAppers/contours2cats#1]
What i got:  ...

2019-11-01 21:15:35.791112: E tensorflow/core/grappler/grappler_item_builder.cc:637] Init node generator/encoder_1/conv2d/kernel/Assign doesn't exist in graph
Traceback (most recent call last):
  File "A:\P2P_V2\pix2pix_lite.py", line 877, in <module>
    main()
  File "A:\P2P_V2\pix2pix_lite.py", line 693, in main
    output_data = converter.convert()
  File "C:\Users\yanfe\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\lite.py", line 898, in convert
    **converter_kwargs)
  File "C:\Users\yanfe\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 404, in toco_convert_impl
    input_data.SerializeToString())
  File "C:\Users\yanfe\AppData\Local\Programs\Python\Python37\lib\site-packages\tensorflow\lite\python\convert.py", line 172, in toco_convert_protos
    "TOCO failed. See console for info.\n%s\n%s\n" % (stdout, stderr))
tensorflow.lite.python.convert.ConverterError: TOCO failed. See console for info.
2019-11-01 21:15:39.031847: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before Removing unused ops: 374 operators, 668 arrays (0 quantized)
2019-11-01 21:15:39.046075: I tensorflow/lite/toco/graph_transformations/graph_transformations.cc:39] Before general graph transformations: 374 operators, 668 arrays (0 quantized)
2019-11-01 21:15:39.217166: F tensorflow/lite/toco/graph_transformations/resolve_constant_unary.cc:234] Unsupported cast op input type
Fatal Python error: Aborted

Current thread 0x00003d28 (most recent call first):
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 33 in execute
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\site-packages\absl\app.py", line 250 in _run_main
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\site-packages\absl\app.py", line 299 in run
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\site-packages\tensorflow\python\platform\app.py", line 40 in run
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\site-packages\tensorflow\lite\toco\python\toco_from_protos.py", line 59 in main
  File "C:\Users\yanfe\AppData\Local\Programs\Python\Python37\Scripts\toco_from_protos.exe\__main__.py", line 9 in <module>
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\runpy.py", line 85 in _run_code
  File "c:\users\yanfe\appdata\local\programs\python\python37\lib\runpy.py", line 193 in _run_module_as_main

**Comment by yanfeiwong** [comment]
Updated to tf 1.15.0 , it works now )
